version: "3.9"
services:
  koha:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    cap_add:
      - DAC_READ_SEARCH
      - SYS_NICE
    environment:
      MYSQL_SERVER: db
      MYSQL_USER: koha_teolib
      MYSQL_PASSWORD: example
      DB_NAME: koha_teolib
      MEMCACHED_SERVERS: memcached:11211
      MB_HOST: rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.koha-staff.rule=Host(`koha-staff.lipniacki.sh`)"
      - "traefik.http.routers.koha-staff.entrypoints=websecure"
      - "traefik.http.routers.koha-staff.tls=true"
      - "traefik.http.routers.hoha-staff.tls.certResolver=sslresolver"
      - "traefik.http.services.koha-staff-lb.loadbalancer.server.port=8081"
      - "traefik.http.routers.koha-opac.rule=Host(`koha.lipniacki.sh`)"
      - "traefik.http.routers.koha-opac.entrypoints=websecure"
      - "traefik.http.routers.koha-opac.tls=true"
      - "traefik.http.routers.hoha-opac.tls.certResolver=sslresolver"
      - "traefik.http.services.koha-opac-lb.loadbalancer.server.port=8080"
    depends_on:
      - db
      - rabbitmq
      - memcached
    networks:
      - koha
      - traefik

  rabbitmq:
      image: docker.io/rabbitmq:3
      volumes:
        - ./rabbitmq_plugins:/etc/rabbitmq/enabled_plugins
      networks:
        - koha

  db:
    image: docker.io/mariadb:11
    volumes:
      - mariadb-koha:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: koha_teolib
      MARIADB_USER: koha_teolib
      MARIADB_PASSWORD: example
    networks:
      - koha

  memcached:
    image: docker.io/memcached
    networks:
      - koha

volumes:
    mariadb-koha:

networks:
  traefik:
    external: true
  koha:
    name: koha
